version: '3'
services:
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8081"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8081"